language: cpp

compiler:
  - gcc
  
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - mv ../ip_filter.tsv ip_filter.tsv
  - cat ip_filter.tsv | ./ip_filter | md5sum
  - cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl - X "DELETE" -uevgeny9042:$BINTRAY_API_KEY "https://api.bintray.com/content/rti/homework/homework01/1/ip_filter-0.0.1-Linux.deb"
  - curl -T ip_filter-0.0.1-Linux.deb -uevgeny9042:$BINTRAY_API_KEY "https://api.bintray.com/content/rti/homework/homework01/1/ip_filter-0.0.1-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
